# -*- coding: utf-8 -*-
"""MachineLearningLPS(29/6/2026).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m1uc5yzH5tNH_T2l0IbvQZUlZG-OLP8x
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
df = pd.read_excel("tarifa.xlsx")
print(df.head())

df = df.apply(pd.to_numeric)

print(df.isnull().sum())

split_df = df["Accesorios"].str.split(",", expand = True)
split_df.columns = [f"Value{i+1}" for i in range(split_df.shape[1])]
split_df = split_df.apply(pd.to_numeric, errors = "coerce").fillna(0)
df = pd.concat([df.drop(columns=["Accesorios"]), split_df], axis = 1)
print(df)

print(df.isnull().sum())

df.fillna(0, inplace=True)

print(df.isnull().sum())

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler

X = df.drop(columns=["Prima"])
Y = df["Prima"]

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

print(X_train.dtypes)

print(X_train.isnull().sum())

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model = RandomForestRegressor()
model.fit(X_train, Y_train)

print("Accuracy: ", model.score(X_test, Y_test))