# -*- coding: utf-8 -*-
"""MachineLearningLPS(29/6/2026).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m1uc5yzH5tNH_T2l0IbvQZUlZG-OLP8x
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
df = pd.read_excel("tarifa.xlsx")
print(df.head())

print(df.isnull().sum())

df.fillna(0, inplace=True)

print(df.isnull().sum())

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler

X = df.drop(columns=["Prima"])
Y = df["Prima"]

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)